// ============================================================
// Password hashing — argon2id with a pepper.
// ============================================================
// The pepper is a server-side secret mixed into every hash. If the
// database is ever leaked, an attacker still needs the pepper to
// run a brute-force — and the pepper lives only in env vars / Vercel.
// ============================================================
// Uses @node-rs/argon2 — pre-compiled Rust bindings with prebuilt
// binaries for every platform Vercel runs on. The original `argon2`
// npm package compiles native C at install time, which fails on
// Vercel's serverless Linux runtime ("No native build was found
// for platform=linux"). Same algorithm + PHC string format, so
// hashes are interoperable: hashes generated by the old `argon2`
// package verify correctly here, and vice-versa.
// ============================================================
import { hash, verify } from '@node-rs/argon2';
// Argon2id is the default in @node-rs/argon2 v2+; no need to pass `algorithm`.

const PEPPER = process.env.PASSWORD_PEPPER || '';
if (!PEPPER) {
  // Fail loudly at boot rather than silently degrading security
  throw new Error('PASSWORD_PEPPER is not set in environment');
}

const PEPPER_BUF = Buffer.from(PEPPER, 'hex');

const ARGON_OPTS = {
  // Memory cost in KiB; 64 MiB — OWASP minimum for 2024
  memoryCost: 65536,
  // Number of iterations
  timeCost: 3,
  // Parallelism (threads)
  parallelism: 1,
  secret: PEPPER_BUF,
};

export async function hashPassword(plain: string): Promise<string> {
  return hash(plain, ARGON_OPTS);
}

export async function verifyPassword(hashStr: string, plain: string): Promise<boolean> {
  try {
    return await verify(hashStr, plain, { secret: PEPPER_BUF });
  } catch {
    return false;
  }
}
